// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2c5f2935-a998-4644-9dac-f34fc3c93899";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAdelanteChange();
void onAtrasChange();
void onDerechaChange();
void onGoChange();
void onIzquierdaChange();

bool adelante;
bool atras;
bool derecha;
bool go;
bool izquierda;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(adelante, READWRITE, ON_CHANGE, onAdelanteChange);
  ArduinoCloud.addProperty(atras, READWRITE, ON_CHANGE, onAtrasChange);
  ArduinoCloud.addProperty(derecha, READWRITE, ON_CHANGE, onDerechaChange);
  ArduinoCloud.addProperty(go, READWRITE, ON_CHANGE, onGoChange);
  ArduinoCloud.addProperty(izquierda, READWRITE, ON_CHANGE, onIzquierdaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
